### PR TITLE
First shot at adding packaging to clatd GIT repo.

### PR DESCRIPTION
**Pull request by davidsummers**
The RPM should be able to be built by going into the packaging/rpm directory
and typing "make".

### CODE REVIEW

**Comment by toreanderson** [comment]
Thanks! I see three issues I'd like you to address before I merge:

1. You're only installing the upstart file (you need the systemd file for Fedora and RHEL7).
2. The NetworkManager dispatcher script isn't included.
3. The manual page isn't included.

**Comment by davidsummers** [comment]
Sorry for the slow reply, I've been busy the last couple of months.  This original try was only for CentOS 6 but I am going to do the CentOS 7 as well.  I hope to have some additions to the PR hopefully today.

**Comment by toreanderson** [comment]
Hi. Since you've initially submitted this issue @ingvarha has already made a spec-file and submitted the result to Fedora, see https://bugzilla.redhat.com/show_bug.cgi?id=1302876 for details. So I'm thinking maybe it would be better if you checked if that worked fine on CentOS 6/7 (I guess it should) and gave positive feedback in the bug report?

**Comment by davidsummers** [comment]
Oh, ok.  Excellant!  That means I don't have to maintain it.  :-)

Thanks for the info.

I saw tayga show up in the EPEL repository but hadn't (yet) seen clatd so I suppose when it finished the review process it will show up and there is a testing version people can work with until then.

Thanks!

**Comment by toreanderson** [comment]
Great! I'll close this PR, then.

**Pull request closed without merging**
